
create user c3 identified by c3;
-- USER SQL
ALTER USER "C3"
DEFAULT TABLESPACE "DEMOS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "C3" QUOTA UNLIMITED ON DEMOS;

-- ROLES
ALTER USER "C3" DEFAULT ROLE "CONNECT","RESOURCE";

grant connect to c3;
-- SYSTEM PRIVILEGES

